// Generated by CoffeeScript 1.3.3
(function() {
  var SimpleHtml5Ruler;

  SimpleHtml5Ruler = (function() {

    function SimpleHtml5Ruler(element, movement) {
      this.element = element;
      ($(this.element)).attr("draggable", "true");
      this.element[0].dataset['movement'] = movement;
      ($(this.element)).on('dragstart', this.dragstart);
      ($(this.element)).on('drag', this.drag);
      ($(this.element)).on('dragend', this.dragend);
    }

    SimpleHtml5Ruler.prototype.dragstart = function(ev) {
      var el;
      if (this.dataset['clone'] !== "true") {
        this.dataset['clone'] = "true";
        el = ($(this)).clone().appendTo('body');
        el[0].dataset['clone'] = "false";
        ($(el)).css('z-index', 0);
        ($(this)).css('z-index', 1);
        return ($(el)).SimpleHtml5Ruler(this.dataset['movement']);
      }
    };

    SimpleHtml5Ruler.prototype.drag = function(ev) {
      if (this.dataset['movement'] === "x") {
        return this.style.left = ev.x + "px";
      } else {
        return this.style.top = ev.y + "px";
      }
    };

    SimpleHtml5Ruler.prototype.dragend = function(ev) {
      return this.style.opacity = 1;
    };

    return SimpleHtml5Ruler;

  })();

  (function($) {
    return $.fn.SimpleHtml5Ruler = function(movement) {
      var ruler;
      if (movement == null) {
        movement = "y";
      }
      return ruler = new SimpleHtml5Ruler(this, movement);
    };
  })($);

}).call(this);
